log_dir_path = "/home/jaster/.local/share/Steam/steamapps/compatdata/8500/pfx/drive_c/users/steamuser/Documents/EVE/logs/Gamelogs/"
search_words = ["hint", "combat", "notify", "bounty"]
stats = ["bounty"]
